name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.organization.name}
website: ${project.url}
main: ${project.groupId}.${project.artifactId}.${project.name}
api-version: 1.15
load: POSTWORLD
softdepend: [ WorldEdit, FastAsyncWorldEdit, PlugMan ]
