name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Zeanon
website: ${project.url}
main: de.zeanon.testutils.TestUtils
depend: [ WorldGuard ]
softdepend: [ PlugMan ]
commands:
  testutils:
    description: The basic command for TestUtils
    aliases: tu
  testblock:
    description: testblock
    aliases: tb
  tnt:
    description: tnt
