name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Zeanon
website: ${project.url}
main: de.zeanon.testutils.TestUtils
api-version: 1.15
softdepend: [ WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan ]
commands:
  testutils:
    description: The basic command for TestUtils
    aliases: [ tu ]
  testblock:
    description: testblock
    aliases: [ tb ]
  tnt:
    description: tnt
